### ISSUE TITLE
No versions displayed

### ISSUE THREAD

**Issue by notuntoward** [timkpaine/jupyterlab_autoversion#11]
After several saves and restarts, I don't see any versions that I could revert to.  The options box remains blank, as shown on screenshot.

I'm running Windows 10 and chrome.

![image](https://user-images.githubusercontent.com/3851891/57045428-69217900-6c22-11e9-836b-7686693f5861.png)

**Comment by timkpaine** [comment]
@notuntoward can you attach the server output as well

**Comment by notuntoward** [comment]
Sure and thanks for looking into this. 

[jlAutoVers.txt](https://github.com/timkpaine/jupyterlab_autoversion/files/3140074/jlAutoVers.txt)
I've attached what I see in the conda console when I open a notebook in jupyterlab, change a line, save it, and the click the autoversion "backwards" icon.  On the screen I see the blank autoversion box as in the previous screenshot.

**Comment by timkpaine** [comment]
@notuntoward the server extension isn't being installed, I added the commands you need to run to the homepage: https://github.com/timkpaine/jupyterlab_autoversion#install

**Comment by timkpaine** [comment]
@notuntoward did this resolve it?

**Comment by notuntoward** [comment]
Yes, that fixed it.

Thanks!

Scott
