### ISSUE TITLE
get 404

### ISSUE THREAD

**Issue by EnchoC** [timkpaine/jupyterlab_autoversion#15]
jupyter lab console
`[W 18:53:35.992 LabApp] 404 GET /autoversion/get?id=&path=XXX/baseline.ipynb (::1) 1.67ms referer=http://localhost:8888/lab`

chrome console
![Screen Shot 2019-08-06 at 6 59 47 PM](https://user-images.githubusercontent.com/28055454/62534795-73d05780-b87c-11e9-96cd-f5fd1c3f0c77.png)

**Comment by timkpaine** [comment]
Did you turn on the server side part of this extension?

**Comment by EnchoC** [comment]
Yes, it get the 404 code when I click the auto-version button

**Comment by timkpaine** [comment]
No, did you follow all 3 of these steps:
https://github.com/timkpaine/jupyterlab_autoversion#install

**Comment by timkpaine** [comment]
```bash
pip install jupyterlab_autoversion
jupyter labextension install jupyterlab_autoversion
jupyter serverextension enable --py jupyterlab_autoversion
```

**Comment by EnchoC** [comment]
jupyterlab-autoversion           0.1.0 

JupyterLab v1.0.4
Known labextensions:
   app dir: /usr/local/share/jupyter/lab
        @jupyterlab/google-drive v1.0.0  enabled  OK
        @jupyterlab/toc v1.0.1  enabled  OK
        @lckr/jupyterlab_variableinspector v0.3.0  enabled  OK
        jupyterlab_autoversion v0.1.0  enabled  OK

has been install

**Comment by timkpaine** [comment]
and the server extension enabled?

**Comment by EnchoC** [comment]
yes, i don't know how to solve it.

**Comment by timkpaine** [comment]
what is the output of `jupyter serverextension list`

**Comment by timkpaine** [comment]
also please provide the output of `pip3 show jupyterlab_autoversion`

**Comment by EnchoC** [comment]
<img width="744" alt="Screen Shot 2019-08-06 at 10 35 33 PM" src="https://user-images.githubusercontent.com/28055454/62549131-8b1e3d80-b89a-11e9-902a-557e5c143d80.png">

**Comment by EnchoC** [comment]
![Screen Shot 2019-08-06 at 10 37 38 PM](https://user-images.githubusercontent.com/28055454/62549306-d0db0600-b89a-11e9-9eba-97d7426dd09e.png)

i think the error because of the place, the `result.value` is undefined
i

**Comment by timkpaine** [comment]
@EnchoC what is the result of `jupyter server extension list`

**Comment by EnchoC** [comment]
<img width="660" alt="Screen Shot 2019-08-07 at 8 08 31 AM" src="https://user-images.githubusercontent.com/28055454/62585267-91d4a100-b8ea-11e9-9bb3-409feb5144ff.png">

**Comment by timkpaine** [comment]
@EnchoC not `jupyter labextension list`, `jupyter serverextension list`

**Comment by EnchoC** [comment]
Thank you, there is no running 3rd install command and I have not installed Jupyter, only installed JupyterLab, it has now been resolved
