### ISSUE TITLE
Serverextension error when installing with docker

### ISSUE THREAD

**Issue by Zireael** [timkpaine/jupyterlab_autoversion#16]
Hi,
I'm building a Jupyter docker image and got this error:

> Step 69/87 : RUN jupyter serverextension enable --py jupyterlab_autoversion
>  ---> Running in ab597b22c6db
> Enabling: jupyterlab_autoversion.extension
> - Writing config: /home/zirdev/.jupyter
>     - Validating...
> Error loading server extension jupyterlab_autoversion.extension
>       X is jupyterlab_autoversion.extension importable?

Docker commands used:
```
RUN pip install --upgrade --no-cache-dir jupyterlab_autoversion
RUN jupyter labextension install jupyterlab_autoversion
RUN jupyter serverextension enable --py jupyterlab_autoversion
```
Is the server extension not compatible with the latest Jupyter  / lab?

**Comment by timkpaine** [comment]
@Zireael should work fine. Could be a dependency issue. is this still a problem?
