### ISSUE TITLE
No previous version showed

### ISSUE THREAD

**Issue by Betristor** [timkpaine/jupyterlab_autoversion#91]
**Describe the bug**
No previous version showed.

**To Reproduce**
1. Create a new notebook
2. Run some code
3. Click the auto version button

**Expected behavior**
Previous versions are shown.

**Screenshots**
<img width="298" alt="image" src="https://user-images.githubusercontent.com/55777837/167179247-b0b62a70-23ed-4aaa-8b83-6062748a8c52.png">

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version:
 - jupyter: 1.0.0
 - jupyterlab: 3.4.0
 - jupyterlab_autoversion: 0.3.6
 - nbconvert: 0.6.5

**Additional context**
```
Traceback (most recent call last):
       File "/opt/tljh/user/lib/python3.9/site-packages/tornado/web.py", line 1702, i>
         result = method(*self.path_args, **self.path_kwargs)
       File "/opt/tljh/user/lib/python3.9/site-packages/tornado/web.py", line 3173, i>
         return method(self, *args, **kwargs)
       File "/home/jupyter-zyh/.local/lib/python3.9/site-packages/jupyterlab_autovers>
         version = int(self.get_argument("version", 0))
     ValueError: invalid literal for int() with base 10: 'undefined'
```

**Comment by timkpaine** [comment]
@Betristor did you save the notebook before you clicked the button to restore an old version? Working fine for me on a fresh jupyterlab 3.4.0 / autoversion 0.3.6 install.

**Comment by Betristor** [comment]
Yep, after I saved the file, a version showed in the panel.
